//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLeaveManagementApp.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeLeaveManagementApp.Content.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} Advance Leaves(s) are available.
        /// </summary>
        public static string Err_AdvanceLeaveBalanceMessage {
            get {
                return ResourceManager.GetString("Err_AdvanceLeaveBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! Your max limit for advance leave is.
        /// </summary>
        public static string Err_AdvanceLeaveMaxLimit {
            get {
                return ResourceManager.GetString("Err_AdvanceLeaveMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the announcement.Try again.
        /// </summary>
        public static string Err_AnnouncementFailed {
            get {
                return ResourceManager.GetString("Err_AnnouncementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} Casual Leave(s) are available,Go for Advance Leave/LOP.
        /// </summary>
        public static string Err_AvailableCasualLeaves {
            get {
                return ResourceManager.GetString("Err_AvailableCasualLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!!  You cannot Apply for Casual/Advance leave since your manager approves the submitted one.
        /// </summary>
        public static string Err_CannotApplyCasualOrAdvanceLeave {
            get {
                return ResourceManager.GetString("Err_CannotApplyCasualOrAdvanceLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!!  You cannot Apply for Comp Off leave since your manager approves the submitted one.
        /// </summary>
        public static string Err_CannotApplyCompOff {
            get {
                return ResourceManager.GetString("Err_CannotApplyCompOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!!  You cannot Apply for LOP leave since your manager approves the submitted one.
        /// </summary>
        public static string Err_CannotApplyLOP {
            get {
                return ResourceManager.GetString("Err_CannotApplyLOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all the fields.
        /// </summary>
        public static string Err_EnterAllFields {
            get {
                return ResourceManager.GetString("Err_EnterAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter content.
        /// </summary>
        public static string Err_EnterContent {
            get {
                return ResourceManager.GetString("Err_EnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter request title.
        /// </summary>
        public static string Err_EnterRequestTitle {
            get {
                return ResourceManager.GetString("Err_EnterRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter title.
        /// </summary>
        public static string Err_EnterTitle {
            get {
                return ResourceManager.GetString("Err_EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty!!.
        /// </summary>
        public static string Err_FieldsCannotEmpty {
            get {
                return ResourceManager.GetString("Err_FieldsCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date is already existing.Please select new date!!.
        /// </summary>
        public static string Err_HolidayDateAlreadyExists {
            get {
                return ResourceManager.GetString("Err_HolidayDateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied for leave/work from home within this date range.
        /// </summary>
        public static string Err_LeaveAlreadyApplied {
            get {
                return ResourceManager.GetString("Err_LeaveAlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave could not be rewarded.
        /// </summary>
        public static string Err_LeaveCouldNotRewarded {
            get {
                return ResourceManager.GetString("Err_LeaveCouldNotRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} LOP(s) are available.
        /// </summary>
        public static string Err_lopLeaveBalanceMessage {
            get {
                return ResourceManager.GetString("Err_lopLeaveBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! Your max limit for LOP is.
        /// </summary>
        public static string Err_LOPMaxLimit {
            get {
                return ResourceManager.GetString("Err_LOPMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Casual Leaves available.
        /// </summary>
        public static string Err_NoCasualLeaves {
            get {
                return ResourceManager.GetString("Err_NoCasualLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be cancelled.
        /// </summary>
        public static string Err_RequestCouldNotCancelled {
            get {
                return ResourceManager.GetString("Err_RequestCouldNotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be sent.
        /// </summary>
        public static string Err_RequestCouldNotSent {
            get {
                return ResourceManager.GetString("Err_RequestCouldNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requested resources must be between 1 and 10.
        /// </summary>
        public static string Err_RequestedResourceNumber {
            get {
                return ResourceManager.GetString("Err_RequestedResourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status could not be changed.
        /// </summary>
        public static string Err_RequestStatusCouldNotChanged {
            get {
                return ResourceManager.GetString("Err_RequestStatusCouldNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request title too long.
        /// </summary>
        public static string Err_RequestTitleTooLong {
            get {
                return ResourceManager.GetString("Err_RequestTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select appropriate values.
        /// </summary>
        public static string Err_SelectAppropriateValues {
            get {
                return ResourceManager.GetString("Err_SelectAppropriateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date is already existing.Please select new date!!.
        /// </summary>
        public static string Err_SelectedDateAlreadyExist {
            get {
                return ResourceManager.GetString("Err_SelectedDateAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee Name,Leave Type and Date Range.
        /// </summary>
        public static string Err_SelectNameandLeaveType {
            get {
                return ResourceManager.GetString("Err_SelectNameandLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select required skills.
        /// </summary>
        public static string Err_SelectRequiredSkills {
            get {
                return ResourceManager.GetString("Err_SelectRequiredSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!!You already applied for Sick Leave today.
        /// </summary>
        public static string Err_SickLeaveAlreadyApplied {
            get {
                return ResourceManager.GetString("Err_SickLeaveAlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value already exists.
        /// </summary>
        public static string Err_ValueAlreadyExists {
            get {
                return ResourceManager.GetString("Err_ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Announcement added successfully.
        /// </summary>
        public static string Msg_CompanyAnnouncementSaved {
            get {
                return ResourceManager.GetString("Msg_CompanyAnnouncementSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee details saved successfully.
        /// </summary>
        public static string Msg_EmployeeDetailsSaved {
            get {
                return ResourceManager.GetString("Msg_EmployeeDetailsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string Msg_HolidayDeleted {
            get {
                return ResourceManager.GetString("Msg_HolidayDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New holiday added successfully.
        /// </summary>
        public static string Msg_HolidaySaved {
            get {
                return ResourceManager.GetString("Msg_HolidaySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully done..
        /// </summary>
        public static string Msg_HolidayUpdated {
            get {
                return ResourceManager.GetString("Msg_HolidayUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request added successfully.
        /// </summary>
        public static string Msg_LeaveAdded {
            get {
                return ResourceManager.GetString("Msg_LeaveAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request successfully submitted for approval.
        /// </summary>
        public static string Msg_LeaveAddedForApproval {
            get {
                return ResourceManager.GetString("Msg_LeaveAddedForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request successfully approved.
        /// </summary>
        public static string Msg_LeaveApproved {
            get {
                return ResourceManager.GetString("Msg_LeaveApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request successfully assigned.
        /// </summary>
        public static string Msg_LeaveAssigned {
            get {
                return ResourceManager.GetString("Msg_LeaveAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request Cancelled.
        /// </summary>
        public static string Msg_LeaveCancelled {
            get {
                return ResourceManager.GetString("Msg_LeaveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request successfully deleted.
        /// </summary>
        public static string Msg_LeaveDeleted {
            get {
                return ResourceManager.GetString("Msg_LeaveDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request rejected.
        /// </summary>
        public static string Msg_LeaveRejected {
            get {
                return ResourceManager.GetString("Msg_LeaveRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave rewarded successfully.
        /// </summary>
        public static string Msg_LeaveRewarded {
            get {
                return ResourceManager.GetString("Msg_LeaveRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOP request added successfully.
        /// </summary>
        public static string Msg_LOPAdded {
            get {
                return ResourceManager.GetString("Msg_LOPAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent successfully.
        /// </summary>
        public static string Msg_MailSent {
            get {
                return ResourceManager.GetString("Msg_MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data value added successfully.
        /// </summary>
        public static string Msg_MasterDateSaved {
            get {
                return ResourceManager.GetString("Msg_MasterDateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password changed successfully.
        /// </summary>
        public static string Msg_PasswordChanged {
            get {
                return ResourceManager.GetString("Msg_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details added successfully.
        /// </summary>
        public static string Msg_ProjectDetailsSaved {
            get {
                return ResourceManager.GetString("Msg_ProjectDetailsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled successfully.
        /// </summary>
        public static string Msg_RequestCancelled {
            get {
                return ResourceManager.GetString("Msg_RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent successfully.
        /// </summary>
        public static string Msg_RequestSent {
            get {
                return ResourceManager.GetString("Msg_RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status changed successfully.
        /// </summary>
        public static string Msg_RequestStatusChanged {
            get {
                return ResourceManager.GetString("Msg_RequestStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource added successfully.
        /// </summary>
        public static string Msg_ResourceAdded {
            get {
                return ResourceManager.GetString("Msg_ResourceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource removed successfully.
        /// </summary>
        public static string Msg_ResourceRemoved {
            get {
                return ResourceManager.GetString("Msg_ResourceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WorkFromHome added successfully.
        /// </summary>
        public static string Msg_WorkFromHomeAdded {
            get {
                return ResourceManager.GetString("Msg_WorkFromHomeAdded", resourceCulture);
            }
        }
    }
}
