//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportEmployee_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateMapping
    {
        public int Id { get; set; }
        public string ActionName { get; set; }
        public int RefTemplateId { get; set; }
    
        public virtual EmailTemplateMaster EmailTemplateMaster { get; set; }
    }
}
