//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityDetail
    {
        public int Id { get; set; }
        public int RefCountryId { get; set; }
        public string City { get; set; }
    
        public virtual CountryDetail CountryDetail { get; set; }
    }
}
