//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidatedEmployeeLeaveDetail
    {
        public int Id { get; set; }
        public int RefEmployeeId { get; set; }
        public Nullable<int> EarnedLeavesCount { get; set; }
        public Nullable<int> AppliedLeavesCount { get; set; }
        public Nullable<int> WorkFromHomeCount { get; set; }
        public Nullable<int> LossofPayCount { get; set; }
        public System.DateTime CreatedBy { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
