//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetail()
        {
            this.EmployeeContactDetails = new HashSet<EmployeeContactDetail>();
            this.EmployeeProjectDetails = new HashSet<EmployeeProjectDetail>();
            this.UserAccounts = new HashSet<UserAccount>();
            this.Workflows = new HashSet<Workflow>();
            this.EmployeeEducationDetails = new HashSet<EmployeeEducationDetail>();
            this.EmployeeExperienceDetails = new HashSet<EmployeeExperienceDetail>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
            this.WorkFromHomes = new HashSet<WorkFromHome>();
            this.EmployeeLeaveTransactions = new HashSet<EmployeeLeaveTransaction>();
            this.EmployeeLeaveTransactionHistories = new HashSet<EmployeeLeaveTransactionHistory>();
            this.EmployeeLeaveMasters = new HashSet<EmployeeLeaveMaster>();
            this.EmployeeLeaveMasters1 = new HashSet<EmployeeLeaveMaster>();
        }
    
        public int Id { get; set; }
        public int RefRoleId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Experience { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string EmpNumber { get; set; }
        public string FirstName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string ImagePath { get; set; }
        public string Bio { get; set; }
        public Nullable<int> RefHierarchyLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContactDetail> EmployeeContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeProjectDetail> EmployeeProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workflow> Workflows { get; set; }
        public virtual MasterDataValue MasterDataValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducationDetail> EmployeeEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeExperienceDetail> EmployeeExperienceDetails { get; set; }
        public virtual MasterDataValue MasterDataValue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFromHome> WorkFromHomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveTransaction> EmployeeLeaveTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveTransactionHistory> EmployeeLeaveTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveMaster> EmployeeLeaveMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveMaster> EmployeeLeaveMasters1 { get; set; }
    }
}
