//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveMaster
    {
        public int Id { get; set; }
        public int RefEmployeeId { get; set; }
        public Nullable<int> LeaveBalance { get; set; }
        public Nullable<int> AppliedLeavesCount { get; set; }
        public Nullable<int> WorkFromHomeCount { get; set; }
        public Nullable<int> LossofPayCount { get; set; }
        public Nullable<int> AdvancedLeaveCount { get; set; }
        public Nullable<int> RewardedLeaveCount { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual EmployeeDetail EmployeeDetail1 { get; set; }
    }
}
