//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRewardedLeaveDetail
    {
        public int Id { get; set; }
        public int RefEmployeeId { get; set; }
        public int RefProjectId { get; set; }
        public int RewardedBy { get; set; }
        public int LeaveCount { get; set; }
        public System.DateTime RewardedDate { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual EmployeeDetail EmployeeDetail1 { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
