//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Location_Facility_Master
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RefCityId { get; set; }
    
        public virtual Geo_Location_City_Master Geo_Location_City_Master { get; set; }
    }
}
