//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geo_Location_State_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Geo_Location_State_Master()
        {
            this.Geo_Location_City_Master = new HashSet<Geo_Location_City_Master>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RefCountryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geo_Location_City_Master> Geo_Location_City_Master { get; set; }
        public virtual Geo_Location_Country_Master Geo_Location_Country_Master { get; set; }
    }
}
