//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_WebAPI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int RefEmployeeId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public int RefNotificationType { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual MasterDataValue MasterDataValue { get; set; }
    }
}
