//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLeaveManagementApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeLeaveManagementApp.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anu@infrrd.ai.
        /// </summary>
        internal static string CC_EMAIL_ID {
            get {
                return ResourceManager.GetString("CC_EMAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,&lt;br/&gt;User detail excel is created successfully.Please find it.&lt;br/&gt;&lt;br/&gt;Regards,&lt;br/&gt;Anu Joseph K.
        /// </summary>
        internal static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string EMAIL_HOST {
            get {
                return ResourceManager.GetString("EMAIL_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string EMAIL_PORT {
            get {
                return ResourceManager.GetString("EMAIL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string EMAIL_SSLON {
            get {
                return ResourceManager.GetString("EMAIL_SSLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anualoor@gmail.com.
        /// </summary>
        internal static string EMAIL_USER_ID {
            get {
                return ResourceManager.GetString("EMAIL_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\ExcelLibrary\SimDataExport.xls.
        /// </summary>
        internal static string EXCEL_SAVING_LOCATION {
            get {
                return ResourceManager.GetString("EXCEL_SAVING_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anualoor@gmail.com.
        /// </summary>
        internal static string FROM_EMAIL_ID {
            get {
                return ResourceManager.GetString("FROM_EMAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mail .
        /// </summary>
        internal static string MAIL_INBOX_HEADER {
            get {
                return ResourceManager.GetString("MAIL_INBOX_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Excel Application.
        /// </summary>
        internal static string SUBJECT {
            get {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anuouseph1991@gmail.com.
        /// </summary>
        internal static string TO_EMAIL_ID {
            get {
                return ResourceManager.GetString("TO_EMAIL_ID", resourceCulture);
            }
        }
    }
}
